apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: 533267068090.dkr.ecr.ap-northeast-2.amazonaws.com/maintomcat:v2.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  clusterIP: 172.20.2.240
  selector:
    app: tomcat
  ports:
  - name: http
    port: 8080
    targetPort: 8080
