apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  annotations:
    kubernetes.io/change-cause: first_version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatt
      name: main
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: tomcatt
        name: main
      containers:
      - image: 533267068090.dkr.ecr.ap-northeast-2.amazonaws.com/maintomcat:v1.0
        name: tomcat
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 250m
            memory: 250Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 3
          
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  clusterIP: 172.20.2.240
  selector:
    app: tomcatt
  ports:
  - name: http
    port: 8080
    targetPort: 8080
