apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-index
  labels:
    app: maintom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintom
  template:
    metadata:
      labels:
        app: maintom
    spec:
      containers:
      - name: tomcat-main
        image: 533267068090.dkr.ecr.ap-northeast-2.amazonaws.com/maintomcat:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  clusterIP: 172.20.2.240
  selector:
    app: maintom
  ports:
  - name: http
    port: 8080
    targetPort: 8080
