apiVersion: v1
kind: Pod
metadata:
  name: tomcattt
  labels:
    app: tomcattt
spec:
  containers:
  - name: tomcattt
    resources:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 250m
        memory: 250Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 60
      timeoutSeconds: 60
      successThreshold: 1
      failureThreshold: 3
    image: 533267068090.dkr.ecr.ap-northeast-2.amazonaws.com/maintomcat:v1.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  clusterIP: 172.20.2.240
  selector:
    app: tomcattt
  ports:
  - name: http
    port: 8080
    targetPort: 8080
