apiVersion: v1
kind: Pod
metadata:
  name: tomcattt
  labels:
    app: tomcattt
spec:
  containers:
  - name: tomcattt
    image: wonjong9504/test:v4.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  clusterIP: 172.20.2.240
  selector:
    app: tomcattt
  ports:
  - name: http
    port: 8080
    targetPort: 8080
